FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build-env

WORKDIR /app
COPY . .

RUN dotnet publish "ReadApi/ReadApi.csproj" -c Release -o /out

# Runtime image
FROM mcr.microsoft.com/dotnet/aspnet:9.0

WORKDIR /app
COPY --from=build-env /out .

ENTRYPOINT dotnet ReadApi.dll
